function love.conf(t)
	t.title = "Material-Love"
	t.author = "Positive07 - Pablo Mayobre"
	t.url = "https://www.github.com/Positive07/material-love"
	t.license = "MIT License - Copyright (c) 2015 Pablo Mayobre"

	t.identity = "Material-Love"						-- The name of the save directory (string)
	t.version = "0.9.0"									-- The LÖVE version this game was made for (string)
	t.console = false									-- Attach a console (boolean, Windows only)
	t.window.title = "Material-Love"					-- The window title (string)
	t.window.icon = "material-love/images/icon32.png"	-- Filepath to an image to use as the window's icon (string)
	t.window.width = 400								-- The window width (number)
	t.window.height = 400								-- The window height (number)
	t.window.borderless = false							-- Remove all border visuals from the window (boolean)
	t.window.resizable = false							-- Let the window be user-resizable (boolean)
	t.window.minwidth = 1								-- Minimum window width if the window is resizable (number)
	t.window.minheight = 1								-- Minimum window height if the window is resizable (number)
	t.window.fullscreen = false							-- Enable fullscreen (boolean)
	t.window.fullscreentype = "desktop"					-- Standard fullscreen or desktop fullscreen mode (string)
	t.window.vsync = true								-- Enable vertical sync (boolean)
	t.window.fsaa = 1									-- The number of samples to use with multi-sampled antialiasing (number)
	t.window.msaa = 1									-- The number of samples to use with multi-sampled antialiasing (number)
	t.window.display = 1								-- Index of the monitor to show the window in (number)
	t.window.highdpi = true								-- Enable high-dpi mode for the window on a Retina display (boolean)
	t.window.srgb = false								-- Enable sRGB gamma correction when drawing to the screen (boolean)
	t.window.x = nil									-- The x-coordinate of the window's position in the specified display (number)
	t.window.y = nil									-- The y-coordinate of the window's position in the specified display (number)

	t.modules.audio = false								-- Enable the audio module (boolean)
	t.modules.event = true								-- Enable the event module (boolean)
	t.modules.graphics = true							-- Enable the graphics module (boolean)
	t.modules.image = true								-- Enable the image module (boolean)
	t.modules.joystick = false							-- Enable the joystick module (boolean)
	t.modules.keyboard = true							-- Enable the keyboard module (boolean)
	t.modules.math = false								-- Enable the math module (boolean)
	t.modules.mouse = true								-- Enable the mouse module (boolean)
	t.modules.physics = false							-- Enable the physics module (boolean)
	t.modules.sound = false								-- Enable the sound module (boolean)
	t.modules.system = true								-- Enable the system module (boolean)
	t.modules.timer = true								-- Enable the timer module (boolean)
	t.modules.window = true								-- Enable the window module (boolean)
	t.modules.thread = false							-- Enable the thread module (boolean)
end